config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :static_pages, only: [:show], param: :slug

  resources :products, only: [:index, :show] do
    member do
      post :add_to_cart, to: 'carts#add'
    end
  end

  resources :categories, only: [:index, :show] do
    member do
      get :products
    end
  end

  resources :accessories, only: [:index, :show]

  resource :cart, only: [:show] do
    patch :update_quantity, to: 'carts#update_quantity'
    delete :remove_item, to: 'carts#remove_item'
    get :checkout, to: 'carts#checkout'
    post :complete_order, to: 'carts#complete_order'
    post :save_user_info, to: 'carts#save_user_info'
  end

  resource :user_info, only: [:edit, :update]

  resources :orders, only: [:index, :show]

  root 'home#index'
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  belongs_to :category
  has_many :carts, as: :cartable

  # Validations
  validates :name, presence: true, length: { maximum: 255 }
  validates :description, length: { maximum: 1000 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :category_id, presence: true, numericality: { only_integer: true }

  def self.ransackable_attributes(auth_object = nil)
    ["name", "description", "price", "quantity_available", "created_at", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["category"]
  end
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :set_accessory, only: %i[show add_to_cart]

  def index
    @q = Accessory.ransack(params[:q])
    @accessories = @q.result.includes(:category)
  end

  def show; end

  def add_to_cart
    cart_item = current_user.carts.find_or_initialize_by(cartable: @accessory)
    cart_item.quantity ||= 0
    cart_item.quantity += params[:quantity].to_i
    if cart_item.save
      flash[:notice] = "Accessory added to cart"
    else
      flash[:alert] = "Failed to add accessory to cart"
    end
    redirect_to accessory_path(@accessory)
  end

  private

  def set_accessory
    @accessory = Accessory.find(params[:id])
  end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/views/accessories/index.html.erb
<h1>Accessories</h1>

<%= search_form_for @q, url: accessories_path, method: :get do |f| %>
  <div>
    <%= f.label :name_cont, "Search by Name" %>
    <%= f.search_field :name_cont %>
  </div>
  <div>
    <%= f.label :category_id_eq, "Filter by Category" %>
    <%= f.collection_select :category_id_eq, Category.all, :id, :name, include_blank: true %>
  </div>
  <div>
    <%= f.submit "Search" %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
    <% @accessories.each do |accessory| %>
      <tr>
        <td><%= link_to accessory.name, accessory_path(accessory) %></td>
        <td><%= accessory.description %></td>
        <td><%= accessory.price %></td>
        <td><%= accessory.category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accessories/show.html.erb
<h1><%= @accessory.name %></h1>
<p><%= @accessory.description %></p>
<p>Price: <%= @accessory.price %></p>
<p>Category: <%= @accessory.category.name %></p>
<%= form_with url: add_to_cart_accessory_path(@accessory), method: :post, local: true do |f| %>
  <%= number_field_tag :quantity, 1, min: 1 %>
  <%= f.submit "Add to Cart" %>
<% end %>
<%= link_to 'Back to Accessories', accessories_path %>